function [measure_data] = postprocessing_quantification_acoustics(sub_id, parameters, medium_masks, output_pressure_file, data)

containers = {
    'pressure_max_brain', ...
    'pressure_max_scalp', ...
    'pressure_max_target', ...
    'pressure_max_offtarget', ...
    'pressure_avg_target', ...
    'pressure_avg_scalp', ...
    'pressure_avg_offtarget', ...
    'pressure_95_brain', ...
    'pressure_95_scalp', ...
    'mechanicalindex_max_whole', ...
    'mechanicalindex_max_brain', ...
    'mechanicalindex_max_scalp', ...
    'FWHM_in_ROI_perc', ...
};

% separately handle FW (considering there are cases where no free water
% data are available)
if ismember('pressure_FW', fieldnames(data))
    containers = [containers, {'pressure_max_FW'}];
end
if ismember('intensity_FW', fieldnames(data))
    containers = [containers, {'intensity_max_FW'}];
end
if ismember('mechanicalindex_FW', fieldnames(data))
    containers = [containers, {'mechanicalindex_max_FW'}];
end

[measure_data] = postprocessing_quantification(sub_id, parameters, medium_masks, containers, output_pressure_file, data);

end