function [measure_data] = postprocessing_quantification_heating(sub_id, parameters, medium_masks, output_pressure_file, data)

containers = {
    'heating_max_brain', ...
    'heating_avg_target', ...
    'maxCEM43_max_whole', ...
    'maxCEM43_max_brain', ...
    'maxCEM43_max_scalp', ...
    'maxCEM43_95_whole', ...
    'maxCEM43_95_brain', ...
    'maxCEM43_95_scalp', ...
};

[measure_data] = postprocessing_quantification(sub_id, parameters, medium_masks, containers, output_pressure_file, data);

end