# 100mm transducers
transducers:
  - name: left # any identifier will do, e.g. serial number, intended target, ...
    n_elements: 10 # number of elements in the transducer
    Elements_ID_mm: [10.0, 22.3, 30.0, 36.3, 41.7, 46.5, 51.0, 55.1, 58.9, 62.5] # minimum ID is not 0 because of the inactive center PCD
    Elements_OD_mm: [21.3, 29.1, 35.3, 40.7, 45.6, 50.0, 54.1, 58.0, 61.6, 65.0]
    curv_radius_mm: 75 # radius of curvature of the bowl 
    dist_to_plane_mm: 65.3 # distance to the transducer plane from the geometric focus
    source_amp: 200608 # [Pa] (72850 calibrated values at 30 W/cm^2 free-water Isppa, 84250 at 40 W/cm^2, 94100 for 50 W/cm^2)
    source_phase_deg: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    source_freq_hz: 300e3 # [Hz] the central frequency # TODO not quite clear what to do with the center PCD (500 kHz)?
    pos_t1_grid: [0, 0, 0] # Position on T1 grid [T1 grid space] (can be left out if importing location data) # TODO find way to read it out parametrically based on subject ID
    focus_pos_t1_grid: [0, 0, 0] # Stimulation target on T1 grid [T1 grid space] (again, can be left out if importing location data) # TODO find way to read it out parametrically based on subject ID (or consider one config per sbj); # TODO consider adding this to transducer (benefits: each transd can have a focus pos)
  
  - name: right  # any identifier will do, e.g. serial number, intended target, ...
    n_elements: 10 # number of elements in the transducer
    Elements_ID_mm: [10.0, 22.1, 29.8, 36.0, 41.4, 46.3, 50.7, 54.9, 58.7, 62.4] # minimum ID is not 0 because of the inactive center PCD
    Elements_OD_mm: [21.1, 28.8, 35.0, 40.4, 45.3, 49.7, 53.9, 57.8, 61.5, 65.0]
    curv_radius_mm: 100 # radius of curvature of the bowl 
    dist_to_plane_mm: 92.7 # distance to the transducer plane from the geometric focus
    source_amp: 200608 # [Pa] (72850 calibrated values at 30 W/cm^2 free-water Isppa, 84250 at 40 W/cm^2, 94100 for 50 W/cm^2)
    source_phase_deg: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    source_freq_hz: 300e3 # [Hz] the central frequency # TODO not quite clear what to do with the center PCD (500 kHz)?
    pos_t1_grid: [0, 0, 0] # Position on T1 grid [T1 grid space] (can be left out if importing location data) # TODO find way to read it out parametrically based on subject ID
    focus_pos_t1_grid: [0, 0, 0] # Stimulation target on T1 grid [T1 grid space] (again, can be left out if importing location data) # TODO find way to read it out parametrically based on subject ID (or consider one config per sbj); # TODO consider adding this to transducer (benefits: each transd can have a focus pos)