close all; clear; clc;

% TODO intensity levels don't quite match, e.g.:
% 


currentFile = matlab.desktop.editor.getActiveFilename;
rootpath = fileparts(currentFile);
cd(rootpath); % repos/PRESTUS_forked/
cd ..;

% add paths
addpath('functions')
addpath(genpath('toolboxes')) 
addpath('/home/common/matlab/fieldtrip/qsub') % uncomment if you are using Donders HPC

%%

parameters = load_parameters('nico_test_double_acoustic_100mm_config.yaml');

% maybe should also check 

%%

% sham = true;
% transducer_ind = 1;
% [parameters, axial_position, intensity_sham] = calculate_transducer_phases( ...
%     parameters, ...
%     transducer_ind, ...
%     90, ...
%     30, ...
%     100, ...
%     sham, ...
%     @create_boxcar, ...
%     true ...
%     );
% 
% transducer = parameters.transducers(transducer_ind);
% velocity = transducer.source_amp/(parameters.medium.water.density*parameters.medium.water.sound_speed);
% 
% p_axial_oneil = focusedAnnulusONeil( ...
%     transducer.curv_radius_mm/1e3, ...
%     [transducer.Elements_ID_mm; transducer.Elements_OD_mm]/1e3, ...
%     velocity, ...
%     transducer.source_phase_rad, ...
%     transducer.source_freq_hz, ...
%     parameters.medium.water.sound_speed, ...
%     parameters.medium.water.density, ...
%     (axial_position-0.5)*1e-3 ... % before here was ax_pos
%     );
% 
% i_axial_oneil_sham = p_axial_oneil.^2/(2*parameters.medium.water.sound_speed*parameters.medium.water.density) .* 1e-4;

%%

sham = false;
transducer_ind = 1;
[parameters, axial_position, intensity_active] = calculate_transducer_phases( ...
    parameters, ...
    transducer_ind, ...
    90, ...
    30, ...
    200, ...
    sham, ...
    @create_boxcar, ...
    true ...
    );

transducer = parameters.transducers(transducer_ind);
velocity = transducer.source_amp/(parameters.medium.water.density*parameters.medium.water.sound_speed);

p_axial_oneil = focusedAnnulusONeil( ...
    transducer.curv_radius_mm/1e3, ...
    [transducer.Elements_ID_mm; transducer.Elements_OD_mm]/1e3, ...
    velocity, ...
    transducer.source_phase_rad, ...
    transducer.source_freq_hz, ...
    parameters.medium.water.sound_speed, ...
    parameters.medium.water.density, ...
    (axial_position-0.5)*1e-3 ... % before here was ax_pos
    );

i_axial_oneil_active = p_axial_oneil.^2/(2*parameters.medium.water.sound_speed*parameters.medium.water.density) .* 1e-4;

%%

figure; hold on;
plot(axial_position, i_axial_oneil_active);
% plot(axial_position, i_axial_oneil_sham);

% TODO how translate source amp and intensity?
velocity = transducer.source_amp/(parameters.medium.water.density*parameters.medium.water.sound_speed);