subject_subfolder: 0 # Should each participants output be stored in a separate folder?

# t1_path_template: /*T1.nii.gz # comment out because want to keep the subject ID from default_config
# t2_path_template: /*T2.nii.gz

transducer: 
  n_elements: 10 # number of elements in the transducer
  # Elements_ID_mm: [0, 31.6988, 44.2688, 53.6688] # TODO from here on
  # Elements_OD_mm: [31.14, 43.71, 53.11, 60.83]
  # TODO unclear to me: previous specs have 0 mm as minimum ID, but with IGT it is 10 mm - is this because of the center PCD?

  Elements_ID_mm: [10.0, 22.3, 30.0, 36.3, 41.7, 46.5, 51.0, 55.1, 58.9, 62.5]
  Elements_OD_mm: [21.3, 29.1, 35.3, 40.7, 45.6, 50.0, 54.1, 58.0, 61.6, 65.0]
  curv_radius_mm: 99.60 # radius of curvature of the bowl # TODO should be ~75!
  dist_to_plane_mm: 92.7 # distance to the transducer plane from the geometric focus
  source_amp: 200608 # [Pa] (72850 calibrated values at 30 W/cm^2 free-water Isppa, 84250 at 40 W/cm^2, 94100 for 50 W/cm^2) # TODO really in Pa? when applying formula, off by factor of ~59.4
  source_phase_deg: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # TODO important to get right? or computed on the fly?
  source_freq_hz: 300e3 # [Hz] the central frequency # TODO not quite clear what to do with the center PCD (500 kHz)?

# expected_focal_distance_mm: 77.0 # expected distance to the stimulation focus # if not specified, then re-calculated during runtime based on target and transducer position
transducer_from_localite: 0 # should we load the transducer locations from the localite file(s)
using_donders_hpc: 0 # are the simulations run on the HPC cluster?

run_posthoc_water_sims: 0
run_heating_sims: 0 # overwritten in multiple places in c_simulation?

medium:
  skull:
    alpha_0_true: 8

# phasic protocol

# thermal:
#   duty_cycle: 0.25 # share of the stimulation duration during which the stimulation is on
#   temp_0: 37 #[deg C] initial temperature, currently not used
#   stim_duration: 2 # [s] stimulation duration within a trial (TODO: difference between stim_duration and on_off_step_duration?)
#   iti: 8 # interval between the trials, from the start of one trial to the start of another [s] (TODO wouldn't "trial_duration" be more accurate?)
#   n_trials: 150 # number of trials to simulate; the total simulated duration is then n_trials*iti seconds  
#   sim_time_steps: 0.005 # [s] simulation time steps during the stimulation period
#   on_off_step_duration: 0.200 # duration of the on+off cycle (200 ms incl. stim on + off)
#   equal_steps: 0 # is the duration of the simulation steps equal for on and off steps? if not, it is computed based on the sim_time_steps * n_steps where n_steps is the needed number of on and off steps derived from the duty cycle

# continuous protocol

thermal:
  duty_cycle: 0.25 # share of the stimulation duration during which the stimulation is on
  temp_0: 37 #[deg C] initial temperature, currently not used
  stim_duration: 0.2 # [s] stimulation duration within a trial (TODO: difference between stim_duration and on_off_step_duration?)
  iti: 0.2 # interval between the trials, from the start of one trial to the start of another [s] (TODO wouldn't "trial_duration" be more accurate?)
  n_trials: 600 # number of trials to simulate; the total simulated duration is then n_trials*iti seconds  
  sim_time_steps: 0.005 # [s] simulation time steps during the stimulation period
  on_off_step_duration: 0.200 # duration of the on+off cycle (200 ms incl. stim on + off)
  equal_steps: 0 # is the duration of the simulation steps equal for on and off steps? if not, it is computed based on the sim_time_steps * n_steps where n_steps is the needed number of on and off steps derived from the duty cycle